PUT http://localhost:3001/api/blogs/5e4a8a72a28e8d39cef20a55
Content-Type: application/json

{
    "title": "Blog Title",
    "author": "Blog Author",
    "url": "some url",
    "likes": 12,
    "user": "5e4a897df818af38be2126e4"
}